language: scala

scala:
  - "2.10.5"

jdk:
  - oraclejdk7

env:
  - SPARK_VERSION=1.4.0 SPARK_PACKAGE_TYPE=hadoop2.6
  - SPARK_VERSION=1.4.1 SPARK_PACKAGE_TYPE=hadoop2.6
  - SPARK_VERSION=1.5.0 SPARK_PACKAGE_TYPE=hadoop2.6
  - SPARK_VERSION=1.5.1 SPARK_PACKAGE_TYPE=hadoop2.6
  - SPARK_VERSION=1.5.2 SPARK_PACKAGE_TYPE=hadoop2.6

addons:
  apt:
    packages:
    - python-virtualenv
  
services:
  - cassandra

script: make clean dist test-travis

sudo: false

