language: scala

scala:
  - "2.10.4"

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - sudo apt-get install -qq python-virtualenv
  
services:
  - cassandra

script: make clean dist test-integration-matrix
