language: scala

scala:
  - "2.10.4"

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
  - sudo apt-get install -qq python-virtualenv
  
services:
  - cassandra

script: make clean dist test-integration-matrix

cache:
  directories:
    - lib
    - $HOME/.m2