language: scala

scala:
  - "2.10.4"

jdk:
  - oraclejdk7

addons:
  apt:
    packages:
    - python-virtualenv
  
services:
  - cassandra

script: make clean dist test-integration-matrix

sudo: false

cache:
  directories:
    - lib
    - $HOME/.m2